# Used https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml as example
package:
  name: ab-plugin-Notebook
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  # Note for future: https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos
  git_rev: main
  git_url: https://github.com/Pan6ora/ab-plugin-Notebook.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - python
    - setuptools
  run:
    - activity-browser-plugin-manager =0.1.0
    - notebook
    - ipywidgets


about:
  home: https://github.com/Pan6ora/ab-plugin-Notebook
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Plugin for Activity Browser
  description: |
    The Activity Browser is a graphical user interface for the [brightway2](https://brightway.dev/)
    advanced life cycle assessment framework.
    Notebook plugin add a Jupyter Notebook inside AB.
